### ISSUE TITLE
Gallery Submission Feedback - wait_for_update should be at least 100ms

### ISSUE THREAD

**Issue by yeeha567** [mtechraw/consent-mode-gtm#1]
When reviewing your template, we've noticed that wait_for_update was set to a default less than 500 milliseconds. When specifying this it's a best practice to give some buffer time to attempt to allow for the updateConsent command to be fired. This is very important when loading the consent management script dynamically.

**Comment by mtechraw** [comment]
Hi @yeeha567 i have updated default value to 200ms kindly review now.

Thank you

**Comment by mtechraw** [comment]
@yeeha567 how long it will take to get approved and listed in Google tag manager template gallery :)
